# Conditions 

---
Allow us to look up into more specific consults


In [1]:
import numpy as np

In [3]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

### Conditionals will returns boolean values for where the conditions is True.

In [4]:
cond_index = arr > 5
cond_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
arr[cond_index]

array([ 6,  7,  8,  9, 10], dtype=int8)

### Multiple conditions

In [6]:
arr[(arr > 5)&(arr < 9)]

array([6, 7, 8], dtype=int8)

In [7]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)