# Copy 

---
| .copy() | allows us to copy a NumPy array into another variable in such a way that when modifying the new array the changes are not reflected in the original array.


In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Let's take a piece from the original array

In [4]:
arr_piece = arr[0:6]
arr_piece

array([0, 1, 2, 3, 4, 5])

In [5]:
arr_piece[:] = 0
arr_piece

array([0, 0, 0, 0, 0, 0])

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
arr_copy = arr.copy()

In [8]:
arr_copy[:] = 100

In [9]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

The data in the original array has been modified because it was still referencing that variable.

With .copy() we create a copy so as not to damage our original array