Arrays can be seen with diferent dimensions for different purpose. These dimensions can be gathered as:

*   |Scalar|: it's regularly a number which  represent a value or data

*   |Matrix|: it's regularly which represent a list of one (1) dimension that  is set algebraically [4,5,6,7], ect.
*   |Tensor|: Regularly seen as time-line or images and it's represented by   more of 3 dimensions. This time-serie can discribe examples, characteristics & its behavior through time.






In [1]:
import numpy as np

## Scalar

In [4]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

## Vector

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

## Matrix

In [6]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]]


2

## Tensor

In [10]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6], [7,8,9], [0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

### If you want to add or eliminate dimensions from the tensor, then, what you have to do is:

In [17]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

### If you want to add or expand just an unique dimension, then you can use:


Use the np.expand dims utility and add the array as the parameter.
Axis=0 will expand just one dimension on row's level; Zero for Python & NumPy is related with rows and 1 is related with columns.

You can allocated it inside an element, for this case "expand" will be a good example


In [19]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [21]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


# Let's the brain workout...

### Making a 5 Dimension Tensor

In [22]:
wk_vector = np.array([[[[[11,12,13]],[[14,15,16]], [[17,18,19]]]]])
print(wk_vector, wk_vector.ndim)

[[[[[11 12 13]]

   [[14 15 16]]

   [[17 18 19]]]]] 5


I've already added one dimension to this Tensor

In [24]:
wk_vector_2 = np.array([[[[[11,12,13]],[[14,15,16]], [[17,18,19]]]]],ndmin=6)
print(wk_vector_2, wk_vector_2.ndim)

[[[[[[11 12 13]]

    [[14 15 16]]

    [[17 18 19]]]]]] 6


### Now, let's squeeze it just for the dimensions used it

In [25]:
sqz_vector = np.squeeze(wk_vector_2)
print(sqz_vector, sqz_vector.ndim)

[[11 12 13]
 [14 15 16]
 [17 18 19]] 2
