NumPy arrays can only contain one data type, as this is what gives it the benefits of memory optimization.

We can know the data type of the array by consulting the .dtype property

In [3]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

By adding the dtype float to the array, lets makes it easier to work with neural networks

In [6]:
arr = np.array([1,2,3,4], dtype = 'float64')
arr.dtype

dtype('float64')

In [7]:
arr

array([1., 2., 3., 4.])

In [9]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [11]:
arr = arr.astype(np.float64)

In [12]:
arr = np.array([1,2,3,4])

arr = arr.astype(np.bool_)
arr

array([ True,  True,  True,  True])

On booleans logic, zero will always be represented as False and the rest of number, Python & NumPy will represent them as True.

In [13]:
arr = np.array([1,2,3,4])

arr = arr.astype(np.string_)
arr

array([b'1', b'2', b'3', b'4'], dtype='|S21')

the np.string_ let NumPy known by know, the integer will be manage as strings

In [14]:
arr = np.array(['1','2','3','4'])

arr = arr.astype(np.int8)
arr

array([1, 2, 3, 4], dtype=int8)