The array is the main object of the library. It represents data in a structured way and can be accessed through indexing, to a specific piece of data or a group of many specific pieces of data.

In [1]:
import numpy as np


Let's define a list and print it. Then let's contrast it with NumPy arrays

In [2]:
list = [1,2,3,4,5,6,7,8,9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr = np.array(list)
type(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Let's now make up a multiple dimension object. Let's create a matrix

In [8]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Let's now focus on Indexing.

1.   It focuses on accessing the different elements or group of elements within the list through the index.
2.   Arrays indexing will start from zero 0 by convention and get into a exact position returning the value in it.



In [11]:
arr
arr[3]

4

Let's move forwards and look into its functionality by adding list and matrix.


In [12]:
arr[0] + arr[5]

7

In [13]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

If now we look into matrix indexing values it will return a set of number which represent the matrix's first element.
To navigate within it, just remember the indexing position:
the first is for row & the second for columns

In [14]:
matrix[0]

array([1, 2, 3])

In [15]:
matrix[0,2]

3

### Slicing



1.   It allows us to extract various data elements and has a beginning and an end.
2.   Numpy will read empty spaces as "all or whole" from the start or the end by convention when slicing is performed. In other words, arra[:2] it's going to be read from the start until index element 2.



---
arr[:] it will read everything.

arr[::3] It'll read everything but read it three by three.

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [20]:
arr[:2]

array([1, 2])

In [21]:
arr[::3]

array([1, 4, 7])

Any value represented by a minus sign(-) will start the indexing from the end to the beginning of the array.

In [22]:
arr[-1]

9

In [23]:
arr[-3:]

array([7, 8, 9])

In [24]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])