# Operations 

---

*   There are different operations that can be used for NumPy arrays.

In [1]:
import numpy as np

In [39]:
list = [1,2]
list

[1, 2]

In [40]:
list * 2

[1, 2, 1, 2]



*     A Python list understands that you want to duplicate the data. It's not what we're looking for. However Numpy understands it much better

Let's perform it on NumPy:



In [41]:
arr = np.arange(0,10)


In [51]:
arr2 = arr.copy()

In [43]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
1 / arr

<ipython-input-45-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [46]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [52]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Let's check it out on Matrix

In [37]:
matrix = arr.reshape(2,5)

In [54]:
matrix2 = matrix.copy()

In [49]:
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
matrix + matrix2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [56]:
matrix - matrix2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [57]:
matrix2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [58]:
np.matmul(matrix, matrix2.T)

array([[ 30,  80],
       [ 80, 255]])

In [59]:
matrix @ matrix2.T

array([[ 30,  80],
       [ 80, 255]])