## There are 2 very relevant functions on arrays (Shape and Reshape). 

The shape of an array will tell us what structure we are working with (size, manipulate, enter).

# Shape

Indicates the shape of the arrangement.

In [2]:
import numpy as np

In [5]:
arr = np.random.randint(1,10, (3,2))
arr.shape
arr

array([[1, 7],
       [6, 1],
       [4, 3]])

# Reshape

Transforms the array as long as the elements reamin as maintained.

In [8]:
arr.reshape(1,6)

array([[1, 7, 6, 1, 4, 3]])

In [9]:
arr.reshape(2,3)

array([[1, 7, 6],
       [1, 4, 3]])

In [11]:
np.reshape(arr,(1,6))

array([[1, 7, 6, 1, 4, 3]])

### You can perform a reshape as C would.

In [12]:
np.reshape(arr,(2,3), 'C')

array([[1, 7, 6],
       [1, 4, 3]])

### You can perform a reshape just like Fortran would.

In [13]:
np.reshape(arr,(2,3), 'F')

array([[1, 4, 1],
       [6, 7, 3]])

# Let's the brain workout

In [51]:
fifth_array = np.random.randint(1,10, (4,2))
fifth_array

array([[7, 1],
       [4, 8],
       [2, 9],
       [9, 6]])

In [52]:
fifth_array.reshape(2,4)

array([[7, 1, 4, 8],
       [2, 9, 9, 6]])